apiVersion: v1
kind: Namespace
metadata:
  name: expense-app

--- 
apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  namespace: expense-app
spec:
  containers:
  - name: nginx
    image: nginx