apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc
spec:
  type: ClusterIP
  selector:
    tier: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
